name: CI

on: 
  pull_request:

jobs:
  enqueue_constable:
    name: Enqueue Constable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Constable Enqueue
        uses: constableapp/github-action@v0.0.71-demo.1f5327e3
        with:
          constable-api-key: ${{ secrets.CONSTABLE_API_KEY }}
          terraform-module-root: "./devops"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github-ref: ${{ github.ref }}
          github-repository:  ${{ github.repository }}
          github-sha: ${{ github.event.pull_request.head.sha || github.sha }}
